version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
            - redis

    nginx:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: alphacomm
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: secret
            MYSQL_USER: alphacomm
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3307:3306"

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - redisdata:/data

    queue:
        build:
            context: .
            dockerfile: Dockerfile
        command: php artisan queue:work --tries=3 --backoff=3
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - app
            - redis

volumes:
    dbdata:
    redisdata:
